version: 0.2
phases:
  build:
    commands:
      - echo packaging JAR file...
      - - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/budget-tracker-app.jar
  discard-paths: yes